### PR TITLE
Test Class bug fixed, added .gitignore and done refactoring.

### PR DESCRIPTION
**Pull request by Modelizer**
I get this error while running test cases.

```
PHP Fatal error:  Class 'Orchestra\Testbench\TestCase' not found in /Users/mudasir/www/fork/lpackager/tests/TestCase.php on line 7

Fatal error: Class 'Orchestra\Testbench\TestCase' not found in /Users/mudasir/www/fork/lpackager/tests/TestCase.php on line 7
```

So i added `Orchestra\Testbench` as a composer require dev dependency.
Then all test pass successfully.

Also added few files on `.gitignore` and done little Refactoring.

Thanks.

### CODE REVIEW

**Comment by Modelizer** [comment]
Also i have a query, how do this [script](https://github.com/amranidev/lpackager/blob/master/composer.json#L28) work? I have gone through documentation but i was not able to figure out.

**Comment by Modelizer** [comment]
I assume `Orchestra\Testbench` should be added by default to `require-dev` part. Because user will not be able to figure out by looking to that error he need to run command `composer run-script testbench` to test app cases unless and until he go to composer to see script section.

What do you think?

**Comment by amranidev** [comment]
@Modelizer , yes I guess, maybe a PR for this.

**Comment by Modelizer** [comment]
I guess now we don't need this [code](https://github.com/amranidev/lpackager/blob/master/composer.json#L28-L30)?

**Comment by amranidev** [comment]
@Modelizer just added that code to make some tests through Travis, but now I think we don't need it at all.

**Comment by Modelizer** [comment]
Ok here we go [PR](https://github.com/amranidev/lpackager/pull/8). :)

**Comment by amranidev** [comment]
yep :octocat: 

thanks a lot.

**Pull request merged**
